### PR TITLE
Fix busy loop on windows

### LINKED ISSUE #76: 100% CPU usage on Windows
I found this problem using fluentd in Windows Server 2012R2.
The debugging results, I think following point is the cause of problem.

```
class MultiWorkerServer < Server
    def run
      while true ### loop very high frequency
        num_alive = keepalive_workers
        break if num_alive == 0
        wait_tick  ### no wait at windows os
      end
    end
end
```

* MultiSpawnServer.wait_tick calls ProcessManager.tick.
  I think there are some problem in ProcessManager.tick method on Windows.

### PR DESCRIPTION
**Pull request by tagomoris**
Fixes #76.

### CODE REVIEW

**Comment by tagomoris** [comment]
@unak Could you check this diff?
And, I think heartbeat can be enabled also on Windows platform. Do you have any idea about any barrier to make it enabled?
https://github.com/treasure-data/serverengine/blob/master/lib/serverengine/process_manager.rb#L173

**Comment by unak** [comment]
@tagomoris I'll check it.  Just a moment...

BTW, Ruby on Windows cannot pass pipes (and any IOs) via file descriptors excepts 0, 1 or 2.
Therefore, we need another mechanism to tell the child processes the heartbeat pipes to enable it.

**Comment by tagomoris** [comment]
@unak I see about it. Thank you for quick comment.

**Comment by tagomoris** [comment]
@unak ping?

**Comment by unak** [comment]
Oh, sorry, I've forgotten to reply.
My conclusion is that it looks good.

**Comment by tagomoris** [comment]
Merged. Thank you @unak!

**Pull request merged**
