### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by ashie**
* GNU/Linux: Migrate to GitHub Actions
* Windows: Stay on AppVeyor, just update Ruby versions
  * Don't migrate to GitHub Actions for now because it seems much heavy than appveyor to fork a process so that it's hard to adjust some fixed timeout values for some tests.

### CODE REVIEW

**Comment by ashie** [comment]
Results: https://github.com/ashie/serverengine/pull/2

**Comment by repeatedly** [comment]
appveyor seems to use ruby 1.9.3 on all matrix.

**Comment by ashie** [comment]
> appveyor seems to use ruby 1.9.3 on all matrix.

Same changes work correctly on my forked repository:
* https://github.com/ashie/serverengine/pull/3
* https://ci.appveyor.com/project/ashie/serverengine/builds/37831708

**Comment by repeatedly** [comment]
Hmm... I see. Merged for testing.

**Comment by ashie** [comment]
Hmm, still failed ...

**Comment by repeatedly** [comment]
ruby 3.0 and ruby 2.7 tests use ruby 1.9 but others use correct version.

**Comment by ashie** [comment]
Now I've found the reason.
`image: Visual Studio 2019` should be added: https://www.appveyor.com/docs/windows-images-software/#ruby
If it's omitted, the image when the project is created is used.

**Comment by repeatedly** [comment]
I changed project setting to use "Vistual Studio 2019". If next commit doesn't change the build image, we need to update appveyor.yml.

**Comment by ashie** [comment]
> If next commit doesn't change the build image, we need to update appveyor.yml.

I've created #111 since the next commit doesn't take effect.

**Pull request merged**
