### PR TITLE
CI: Add Ruby 3.2

### PR DESCRIPTION
**Pull request by ashie**
Signed-off-by: Takuro Ashie <ashie@clear-code.com>

### CODE REVIEW

**Comment by daipom** [comment]
I also ran into the same problem.
This is caused by the old `rake` version.
We need this fix for `rake`.

* https://github.com/ruby/rake/pull/297

This means we need to update `rake` and `rspec`.

**Comment by ashie** [comment]
I tried it once but not yet completed, some tests stalls on latest RSpec.

**Comment by ashie** [comment]
Oh? Now I've test them locally and succeeded without any problems.
Fixed by upstream?

**Comment by ashie** [comment]
CI succeeded on all environments.

**Comment by daipom** [comment]
Yay! Thanks!

**Pull request merged**
